title: Max Young

name: MaxYoung's homepage
description:  I am Max Young
# url: https://max-young.github.io
url: .

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Beijing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
# gems:
plugins:
  - jekyll-sitemap
