- name: Kanban
  image: kanban.png
  url: ""
  oneliner: 
  role: Solo Full-Stack Developer
  description: >
    Independently developed a comprehensive Kanban-based project management system tailored for autonomous driving operations.
    The system significantly improved accident management processes, contributing to a reduction in the accident rate from 13 to 7 per 10,000 kilometers within six months.
    It facilitated efficient delivery of dozens of new routes and enhanced team collaboration by effectively bridging the communication gap between R&D and operations teams.
    This solution streamlined workflow visibility and task tracking across departments, resulting in more coordinated project execution and improved safety outcomes.
  technologies:
    - Python(Flask)
    - React(Create React App)
    - Ant Design

- name: OTA management system
  image: ota_management_system.png
  url: ""
  oneliner: 
  role: Lead Developer
  description:
    A 2D game developed with C++ and OpenGL, although it is 2D, it reflects a lot of knowledge of computer graphics and OpenGL development methods.
    This project uses framebuffer and irrKlang to achieve some interesting effects, enjoy it.
  technologies:
    - Python(Flask)
    - React
    - Ant Design

- name: Vehicle Calibration Software
  image: vehicle_calibration_software.png
  url: ""
  oneliner: 
  role: Lead Developer
  description:
    A 2D game developed with C++ and OpenGL, although it is 2D, it reflects a lot of knowledge of computer graphics and OpenGL development methods.
    This project uses framebuffer and irrKlang to achieve some interesting effects, enjoy it.
  technologies:
    - Python(Flask)
    - React
    - Ant Design

- name: Hit Bricks Game
  image: hitbricksgame.png
  url: https://github.com/max-young/hit-bricks-game
  oneliner: A simple 2D game
  role: Lead Developer
  description:
    A 2D game developed with C++ and OpenGL, although it is 2D, it reflects a lot of knowledge of computer graphics and OpenGL development methods.
    This project uses framebuffer and irrKlang to achieve some interesting effects, enjoy it.
  technologies:
    - C++
    - OpenGL

- name: OpenGL Rendering
  image: opengl_rendering.png
  url: https://github.com/max-young/opengl_study
  oneliner: opengl rendering collection
  role: Developer
  description:
    Realistic PBR is realized by using OpenGL and GLSL. Different spheres have different normal distribution and roughness, so as to calculate different NDF and mask functions, and then calculate different fresnel equation reflectivity according to different metallic, so as to calculate Different BRDFs get different lighting effects.
    This also includes the effect of using cubemap to get skybox.
  technologies:
    - C++
    - OpenGL

- name: KaoShiXing
  image: kaoshixing.png
  url: https://www.kaoshixing.com/
  oneliner: Online Exam System
  role: Lead Developer
  description: >
    KaoShiXing is a toB online exam system, which can meet the requirements of employee training exams, dealer exams, recruitment exams, knowledge contests, homework, practice exams, etc.
    I lead the design, construction and development of this project, and have gone through the process from zero to 1,000 enterprise users. The work includes system design, front-end and back-end development, deployment, operation and maintenance.
  technologies:
    - Python
    - Flask
    - MySQL
    - MongoDB
    - JQuery
    - AliYun
